import { useEffect, useMemo, useState } from 'react'
import { Accordion, Alert, Badge, Button, Carousel, Col, Container, Form, ListGroup, Modal, Row } from 'react-bootstrap'
import './App.css'
import StoreNavbar from './components/StoreNavbar'
import Footer from './components/Footer'
import ProductCard from './components/ProductCard'
import { money, products } from './data'

const pages = ['inicio', 'productos', 'detalle', 'carrito', 'pago', 'contacto']
function Heading({ eyebrow, title, text }) { return <div className="section-heading"><span>{eyebrow}</span><h1>{title}</h1>{text && <p>{text}</p>}</div> }

export default function App() {
  const hash = window.location.hash.replace('#/', '')
  const [page, setPage] = useState(pages.includes(hash) ? hash : 'inicio')
  const [selected, setSelected] = useState(products[0])
  const [cart, setCart] = useState([])
  const [quick, setQuick] = useState(null)
  const [toast, setToast] = useState('')
  useEffect(() => { const sync = () => { const value = window.location.hash.replace('#/', ''); setPage(pages.includes(value) ? value : 'inicio') }; window.addEventListener('hashchange', sync); return () => window.removeEventListener('hashchange', sync) }, [])
  const navigate = next => { window.location.hash = `/${next}`; setPage(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const add = product => { setCart(old => old.some(x => x.id === product.id) ? old.map(x => x.id === product.id ? {...x, qty:x.qty+1} : x) : [...old, {...product, qty:1}]); setToast(`${product.name} se agregó al carrito`); window.setTimeout(() => setToast(''), 2500) }
  const detail = product => { setSelected(product); navigate('detalle') }
  const common = { add, detail, setQuick }
  return <div className="app-shell"><StoreNavbar page={page} navigate={navigate} cartCount={cart.reduce((s,x)=>s+x.qty,0)} />{toast && <div className="cart-toast" role="status">✓ {toast}</div>}<main>
    {page === 'inicio' && <Home navigate={navigate} {...common} />}{page === 'productos' && <Catalog {...common} />}{page === 'detalle' && <Detail product={selected} add={add} navigate={navigate} />}{page === 'carrito' && <Cart cart={cart} setCart={setCart} navigate={navigate} />}{page === 'pago' && <Checkout cart={cart} setCart={setCart} navigate={navigate} />}{page === 'contacto' && <Contact />}
  </main><Footer navigate={navigate}/><Quick product={quick} close={()=>setQuick(null)} add={add} detail={detail}/></div>
}

function Home({ navigate, add, detail, setQuick }) { return <>
  <Carousel className="hero-carousel" fade interval={5000}>{[
    ['hero-one','NUEVA COLECCIÓN · 2026',<>Tu belleza.<br/><em>Tu momento.</em></>,'Descubre fórmulas que cuidan tu piel y realzan lo mejor de ti.','Explorar colección'],
    ['hero-two','RUTINA ESENCIAL',<>Un acabado<br/><em>natural.</em></>,'La cobertura que quieres, la ligereza que tu piel necesita.','Conocer la base'],
    ['hero-three','COLOR SIN LÍMITES',<>Crea tu propio<br/><em>look.</em></>,'Tonos versátiles para expresarte a tu manera.','Ver tendencias']
  ].map((slide,i)=><Carousel.Item key={slide[0]}><div className={`hero-slide ${slide[0]}`}><Container><div className="hero-copy"><span className="eyebrow">{slide[1]}</span><h1>{slide[2]}</h1><p>{slide[3]}</p><Button onClick={()=>i===1?detail(products[0]):navigate('productos')}>{slide[4]} →</Button></div></Container></div></Carousel.Item>)}</Carousel>
  <section className="benefits"><Container><Row>{[['◇','Envíos a todo el país','Gratis desde $50'],['♧','Fórmulas seleccionadas','Calidad garantizada'],['♡','Compra con confianza','Pago 100% seguro'],['↻','Devoluciones fáciles','Hasta 15 días']].map(x=><Col xs={6} lg={3} key={x[1]}><div><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div></Col>)}</Row></Container></section>
  <section className="section-space"><Container><Heading eyebrow="LOS FAVORITOS" title="Elegidos para ti" text="Una selección de nuestros productos más amados."/><Row className="g-4">{products.slice(0,4).map(p=><Col md={6} lg={3} key={p.id}><ProductCard product={p} onAdd={add} onDetail={detail} onQuickView={setQuick}/></Col>)}</Row><div className="text-center mt-5"><Button variant="outline-dark" onClick={()=>navigate('productos')}>Ver catálogo completo →</Button></div></Container></section>
  <section className="beauty-note"><Container><Row className="align-items-center"><Col lg={6}><div className="note-image"/></Col><Col lg={6}><div className="note-copy"><span>NUESTRA FILOSOFÍA</span><h2>Belleza real,<br/><em>todos los días.</em></h2><p>Creemos que el maquillaje no te transforma: revela lo que ya existe. Elegimos productos versátiles, cómodos y creados para acompañar tu ritmo.</p><Button variant="link" onClick={()=>navigate('contacto')}>Conoce más sobre nosotros →</Button></div></Col></Row></Container></section>
  </> }

function Catalog({ add, detail, setQuick }) {
  const [category,setCategory]=useState('Todos'), [query,setQuery]=useState('')
  const shown=products.filter(p=>(category==='Todos'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase()))
  return <section className="page-section"><Container><Heading eyebrow="NUESTRO CATÁLOGO" title="Encuentra tu favorito" text="Maquillaje de alta calidad para looks naturales o profesionales."/><div className="catalog-tools"><div>{['Todos','Rostro','Ojos','Labios'].map(c=><Button key={c} variant={category===c?'dark':'outline-dark'} onClick={()=>setCategory(c)}>{c}</Button>)}</div><Form.Control aria-label="Buscar productos" placeholder="Buscar producto..." value={query} onChange={e=>setQuery(e.target.value)}/></div><Row className="g-4">{shown.map(p=><Col sm={6} lg={4} key={p.id}><ProductCard product={p} onAdd={add} onDetail={detail} onQuickView={setQuick}/></Col>)}</Row>{!shown.length&&<Alert variant="light" className="text-center mt-4">No encontramos productos.</Alert>}</Container></section>
}

function Detail({ product, add, navigate }) { return <section className="page-section"><Container><button className="back-link" onClick={()=>navigate('productos')}>← Volver al catálogo</button><Row className="detail-layout align-items-center"><Col lg={6}><div className="detail-image"><img src={product.image} alt={product.name}/><Badge>{product.badge}</Badge></div></Col><Col lg={6}><div className="detail-copy"><span>{product.category}</span><h1>{product.name}</h1><div className="rating">★★★★★ <span>{product.rating} · 128 reseñas</span></div><div className="detail-price">{money(product.price)}</div><p>{product.description} Fórmula ligera que unifica el tono sin sensación pesada y mantiene la piel cómoda durante todo el día.</p><h3>Selecciona tu tono</h3><div className="swatches">{['#f3d6c1','#dbb193','#bd8065','#8e553e','#5b3427'].map(c=><button key={c} style={{background:c}} aria-label={`Tono ${c}`}/>)}</div><Button size="lg" onClick={()=>add(product)}>Añadir al carrito · {money(product.price)}</Button></div></Col></Row><Accordion className="product-accordion" defaultActiveKey="0"><Accordion.Item eventKey="0"><Accordion.Header>Características y beneficios</Accordion.Header><Accordion.Body><ListGroup variant="flush">{['Cobertura media a alta, fácil de modular','Acabado natural y luminoso','Fórmula ligera de larga duración','Apta para todo tipo de piel'].map(x=><ListGroup.Item key={x}>{x}</ListGroup.Item>)}</ListGroup></Accordion.Body></Accordion.Item><Accordion.Item eventKey="1"><Accordion.Header>Ingredientes y modo de uso</Accordion.Header><Accordion.Body>Agita antes de usar. Aplica desde el centro del rostro y difumina hacia afuera.</Accordion.Body></Accordion.Item><Accordion.Item eventKey="2"><Accordion.Header>Envíos y devoluciones</Accordion.Header><Accordion.Body>Envío de 2 a 5 días hábiles y devoluciones durante 15 días.</Accordion.Body></Accordion.Item></Accordion></Container></section> }

function Cart({ cart,setCart,navigate }) {
  const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0), update=(id,n)=>setCart(cart.map(x=>x.id===id?{...x,qty:Math.max(1,x.qty+n)}:x))
  return <section className="page-section"><Container><Heading eyebrow="TU SELECCIÓN" title="Carrito de compras" text="Revisa tus productos antes de finalizar la compra."/>{!cart.length?<Empty navigate={navigate}/>:<Row className="g-5"><Col lg={8}><div className="cart-list">{cart.map(x=><div className="cart-item" key={x.id}><img src={x.image} alt=""/><div className="cart-info"><small>{x.category}</small><h3>{x.name}</h3><div className="quantity"><button onClick={()=>update(x.id,-1)}>−</button><span>{x.qty}</span><button onClick={()=>update(x.id,1)}>+</button></div></div><strong>{money(x.price*x.qty)}</strong><button className="remove" onClick={()=>setCart(cart.filter(i=>i.id!==x.id))}>Eliminar</button></div>)}</div></Col><Col lg={4}><Summary total={subtotal} checkout={()=>navigate('pago')}/></Col></Row>}</Container></section>
}
function Empty({navigate}) { return <div className="empty-state"><span>🛍</span><h2>Tu carrito está esperando</h2><p>Explora el catálogo y encuentra algo que te encante.</p><Button onClick={()=>navigate('productos')}>Descubrir productos</Button></div> }
function Summary({total,checkout}) { const shipping=total>=50?0:4.99; return <div className="order-summary"><h2>Resumen</h2><p><span>Subtotal</span><strong>{money(total)}</strong></p><p><span>Envío</span><strong>{shipping?'$4.99':'Gratis'}</strong></p><hr/><p className="total"><span>Total</span><strong>{money(total+shipping)}</strong></p>{checkout&&<><Button onClick={checkout}>Finalizar compra →</Button><small>🔒 Pago seguro y protegido</small></>}</div> }

function Checkout({cart,setCart,navigate}) {
  const [done,setDone]=useState(false), total=useMemo(()=>cart.reduce((s,x)=>s+x.price*x.qty,0),[cart]); const submit=e=>{e.preventDefault();setDone(true);setCart([])}
  if(done)return <section className="page-section"><Container><div className="empty-state success"><span>✓</span><h1>¡Gracias por tu compra!</h1><p>Tu pedido fue registrado correctamente. Pronto recibirás una confirmación.</p><Button onClick={()=>navigate('inicio')}>Volver al inicio</Button></div></Container></section>
  return <section className="page-section"><Container><Heading eyebrow="ÚLTIMO PASO" title="Pago seguro" text="Completa tus datos para confirmar el pedido."/>{!cart.length&&<Alert variant="warning">Tu carrito está vacío. Agrega productos antes de pagar.</Alert>}<Row className="g-5"><Col lg={7}><Form className="checkout-form" onSubmit={submit}><h2>Datos de contacto</h2><Row><Col md={6}><Form.Group><Form.Label>Nombre completo</Form.Label><Form.Control required placeholder="Dayna Meza"/></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Correo electrónico</Form.Label><Form.Control required type="email" placeholder="correo@ejemplo.com"/></Form.Group></Col></Row><h2>Información de pago</h2><Form.Group><Form.Label>Número de tarjeta</Form.Label><Form.Control required inputMode="numeric" pattern="[0-9 ]{15,19}" placeholder="0000 0000 0000 0000"/></Form.Group><Row><Col><Form.Group><Form.Label>Vencimiento</Form.Label><Form.Control required pattern="[0-9]{2}/[0-9]{2}" placeholder="MM/AA"/></Form.Group></Col><Col><Form.Group><Form.Label>CVV</Form.Label><Form.Control required pattern="[0-9]{3,4}" placeholder="123"/></Form.Group></Col></Row><Form.Check required label="Confirmo que los datos ingresados son correctos."/><Button type="submit" disabled={!cart.length}>Pagar {money(total)}</Button></Form></Col><Col lg={5}><div className="order-summary"><h2>Tu pedido</h2>{cart.map(x=><p key={x.id}><span>{x.name} × {x.qty}</span><strong>{money(x.price*x.qty)}</strong></p>)}<hr/><p className="total"><span>Total</span><strong>{money(total)}</strong></p></div></Col></Row></Container></section>
}

function Contact(){const[sent,setSent]=useState(false);return <section className="page-section contact-page"><Container><Heading eyebrow="HABLEMOS" title="Estamos para ayudarte" text="¿Tienes una pregunta sobre un producto o tu pedido? Escríbenos."/><Row className="g-5"><Col lg={5}><div className="contact-info">{[['✉','Correo','hola@dmbeauty.com'],['⌕','Ubicación','Guatemala, Guatemala'],['◷','Horario','Lunes a viernes · 8:00–17:00']].map(x=><div key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></Col><Col lg={7}>{sent&&<Alert variant="success">¡Mensaje enviado! Te responderemos muy pronto.</Alert>}<Form className="contact-form" onSubmit={e=>{e.preventDefault();setSent(true);e.currentTarget.reset()}}><Row><Col md={6}><Form.Group><Form.Label>Nombre</Form.Label><Form.Control required placeholder="Tu nombre"/></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Correo electrónico</Form.Label><Form.Control required type="email" placeholder="tu@correo.com"/></Form.Group></Col></Row><Form.Group><Form.Label>Asunto</Form.Label><Form.Select required defaultValue=""><option value="" disabled>Selecciona una opción</option><option>Consulta de producto</option><option>Estado de mi pedido</option><option>Cambios y devoluciones</option></Form.Select></Form.Group><Form.Group><Form.Label>Mensaje</Form.Label><Form.Control required as="textarea" rows={5} placeholder="Cuéntanos cómo podemos ayudarte..."/></Form.Group><Button type="submit">Enviar mensaje →</Button></Form></Col></Row></Container></section>}

function Quick({product,close,add,detail}){return <Modal show={!!product} onHide={close} centered size="lg"><Modal.Header closeButton><Modal.Title>Vista rápida</Modal.Title></Modal.Header>{product&&<Modal.Body><Row className="align-items-center"><Col md={6}><img className="modal-product-img" src={product.image} alt={product.name}/></Col><Col md={6}><small>{product.category}</small><h2>{product.name}</h2><div className="rating">★★★★★ <span>{product.rating}</span></div><p>{product.description}</p><h3>{money(product.price)}</h3><Button onClick={()=>{add(product);close()}}>Añadir al carrito</Button><Button variant="link" onClick={()=>{detail(product);close()}}>Ver ficha completa →</Button></Col></Row></Modal.Body>}</Modal>}
